CC = gcc
CFLAGS = -Wall -Wextra -std=c99
LDFLAGS =
SRC = $(wildcard ./*.c)
OBJ = $(SRC:.c=.o)
EXEC = myprogram

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(LDFLAGS) $^ -o $@ `mysql_config --cflags --libs`

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@ `mysql_config --cflags --libs`

clean:
	rm -f $(OBJ) $(EXEC)
